### ISSUE TITLE
uncaught reference error in index.html

### ISSUE THREAD

**Issue by socialcred** [gfoss/misc#1]
I finally got around to trying the code on my Pineapple.  I get a beautiful captive portal, but the user input doesn't get saved to auth.log, and the user can't get past the captive portal page.  Have you guys had the same problem with yours?  I am using evil portal 2.4 and pinapple firmware 2.2.0.  

Using Chrome developer tools it cites an error on the index.html page, uncaught reference error: $ is not defined at this line:

$("#login").submit();

Any thoughts on how to fix this?

**Comment by gfoss** [comment]
Great catch! I completely forgot to attach JQuery to this repo and define this within the code. The error that you are observing here is because this script is missing and this is a required piece. I'll modify this and will have a new commit up soon. Thank you.
